import numpy as np

# AB


class Locations:
    locations = {
        0: "Montgomery, AL",
        1: "Phoenix, AZ",
        2: "Little Rock, AR",
        3: "Sacramento, CA",
        4: "Denver, CO",
        5: "Hartford, CT",
        6: "Dover, DE",
        7: "Tallahassee, FL",
        8: "Atlanta, GA",
        9: "Boise, ID",
        10: "Springfield, IL",
        11: "Indianapolis, IN",
        12: "Des Moines, IA",
        13: "Topeka, KS",
        14: "Frankfort, KY",
        15: "Baton Rouge, LA",
        16: "Augusta, ME",
        17: "Annapolis, MD",
        18: "Boston, MA",
        19: "Lansing, MI",
        20: "St. Paul, MN",
        21: "Jackson, MS",
        22: "Jefferson City, MO",
        23: "Helena, MT",
        24: "Lincoln, NE",
        25: "Carson City, NV",
        26: "Concord, NH",
        27: "Trenton, NJ",
        28: "Santa Fe, NM",
        29: "Albany, NY",
        30: "Raleigh, NC",
        31: "Bismarck, ND",
        32: "Columbus, OH",
        33: "Oklahoma City, OK",
        34: "Salem, OR",
        35: "Harrisburg, PA",
        36: "Providence, RI",
        37: "Columbia, SC",
        38: "Pierre, SD",
        39: "Nashville, TN",
        40: "Austin, TX",
        41: "Salt Lake City, UT",
        42: "Montpelier, VT",
        43: "Richmond, VA",
        44: "Olympia, WA",
        45: "Charleston, WV",
        46: "Madison, WI",
        47: "Cheyenne, WY",
    }
